/**
 * Express Request type augmentation.
 *
 * Extends the Express `Request` interface with application-specific properties
 * that are attached by middleware before route handlers execute.
 */
declare global {
  namespace Express {
    interface Request {
      /** UUID v4 generated by correlationId middleware for every inbound request. */
      correlationId: string;
      /** Authenticated user payload attached by auth middleware. */
      user?: { userId: string; role: string };
    }
  }
}

export {};
